### PR TITLE
Fix grammar and flow.

### PR DESCRIPTION
**Pull request by IonoclastBrigham**
Replaced a few mistranslations.
Fixed some basic grammatical errors (mood, plurality, etc.).
Made a bunch of minor changes where the sentence wasn't necessarily ungrammatical, but would be awkward to a native speaker.

### CODE REVIEW

**Comment by IonoclastBrigham** [comment]
Commas are a tricky subject, and people (especially young students and ESL/EFL speakers) tend to use far too many. This is doubly true when they try to make one sentence where there should really be two. There were a few places where I may have used unnecessary commas; but, that is a matter of taste and style, and how you want the text to flow and feel.

**Comment by ludamad** [comment]
English native speaker from Canada, I'll chime in with my grammar analysis if it's at all useful:

"It works by generating LuaJIT bytecode, including debug information, and uses LuaJIT's virtual machine to run the generated bytecode."
This stylistic choice improves the sentence in my opinion. Here "including debug information" is a comma-delimited phrases and marks the phrase as tangential to the main topic, which fits to me here.

"On its own, the language toolkit does not do anything useful, since LuaJIT itself does the same things natively."
This sentence, and the variation with the first comma dropped, seem most natural to me. Dropping all commas would not.

**Comment by IonoclastBrigham** [comment]
@ludamad thanks for chiming in. Always good to have an outside source to keep ya honest.

**Comment by franko** [comment]
Thanks to both of you, your advices are very useful for me. It is not always simple for me to choose where to use commas. It seems that often is a matter of taste but I think I‘ve got the feeling of how I should use them.

Otherwise I could have avoided many other errors by paying more attention. I will be more careful the next time. Sometimes I value more the content then the grammar correctness but of course both of them are important.

I will also try to “engrave” in my mind that, for some obscure reasons, the word “information” is not used in plural form :-)

**Comment by IonoclastBrigham** [comment]
In English, information is a grouping word. You can think of it as a
container full of individual pieces of information. "Piece" is the only way
we can specify that information is actually singular.

Paper can behave similarly, depending on how it's being used. "All this
paper" versus "all these papers". The first form refers to many individual
sheets of paper (sheet is the singular specifier), while the second form
would refer to papers in the sense of "scholarly research reports".

There's lots of these words, and the rules, if they exist, are somewhat
obscure; I think most native speakers use them intuitively, by "feel".

**Pull request merged**
