### PR TITLE
Adding test case and fix for #26

### PR DESCRIPTION
**Pull request by gnois**
Added test case for gnois/luajit-lang-toolkit#2

For #26, the `string.format("%q", ...)` seems not able to print escapes such as \n, \r verbatim no matter how I try. 
Anyhow I am not sure if the fix is the best way.

### CODE REVIEW

**Comment by franko** [comment]
Sorry, I was not clear. I mean:

```lua
function escape(val)
    local q = string.format("%q", val)
    return string.gsub(q, "\\\n", "\\n")
end
```

As for the implementation differences of "%q" I don't think that's a real issue. For me luajit's "%q" implementation is fine, except the problem with "\n" you was pointing out.
Re-implementing such a function in Lua can be very costly and should be avoided IMHO.

**Comment by gnois** [comment]
What about other escapes like `\r \f \t \\ \' \" ` ?

**Comment by franko** [comment]
Ok, I see your point. I think it is ok to merge your proposition.

Now I'm just wondering why in your "escape" function \' and \" are not in the list of all the other escape sequences. You are calling gsub for them outside of the for loop but I don't see why they are not treated like the others, in the for loop.

**Comment by franko** [comment]
Ok, I found something cool with just one gsub call:

```lua
local function replace(c)
    local esc = {
        ['\a'] = [[\a]], ['\b'] = [[\b]], ['\f'] = [[\f]], ['\n'] = [[\n]], ['\r'] = [[\r]], ['\t'] = [[\t]], ['\v'] = [[\v]], ['\''] = [[\']], ['\"'] = [[\"]]
    }
    return esc[c] and esc[c] or ('\\' .. string.format("%d", string.byte(c)))
end

local function escape(s)
    return string.gsub(s, "%c", replace)
end
```
I didn't make any measurement but I think it should be more fast to execute. With this function the string is scanned just one time and no temporary strings are created except the bit to represent a char in decimal notation.

**Comment by gnois** [comment]
Yeah, that sounds better! I am not aware that there's a pattern that match control chars.  :)
I have to add some changes still, because the "%c" does not catch `\\ \"` which are non-control chars.
```
local function replaceEsc(c)
    local esc = {
        ['\a'] = [[\a]], ['\b'] = [[\b]], ['\f'] = [[\f]], ['\n'] = [[\n]], ['\r'] = [[\r]], ['\t'] = [[\t]], ['\v'] = [[\v]]
    }
    return esc[c] or string.format("\\%d", string.byte(c))
end

local function replacePunc(c)
    local esc = {
        ['\\'] = [[\\]], ['"'] = [[\"]]  -- \' not needed since we quote with double quotes
    }
    return esc[c] or c
end

local function escape(s)
    s = string.gsub(s, "%p", replacePunc)
    return string.gsub(s, "%c", replaceEsc)
end
```
Without the change, the following would not pass.
```
print("\\\n\r\"'\'\0")
print('\v\\\t\"\'')
```

Forget about my previous implementation. The `\\` is out of the loop because I think it has to be replaced earlier than the control chars, as pairs() does not observe ordering. The `\' and \"` are outside without good reason, other than they are punctuations like `\\`, which is non sense.

**Comment by franko** [comment]
Ok, I found a good solution and I made the change directly in the master branch. Here the commit frank@738f577070510df6e7d73eed5ee1d3ad3daed9d2.

**Comment by gnois** [comment]
Alright, thanks.

**Pull request closed without merging**
